### PR TITLE
Complete overhaul of this project to make it compatible to Angular 4.…

### PR DESCRIPTION
**Pull request by ThorstenBux**
…2.x. Example is a project generated with ```ng new``` and enhanced using the agular2-click-to-edit components. Library compiles using new tsconfig.json.

Works fine for me. Please let me know if you are going to make a new npm release otherwise I'll do it under a new name.

### CODE REVIEW

**Comment by ThorstenBux** [comment]
Oh, I was just going to rework that again. Sorry for that but somehow I didn't change your latest changes from master.
Meaning the permission tag is lost and the selectors are all broken. Sorry for that :-/

**Comment by nadavshemesh** [comment]
Hey dont worry about it i can revert it, 
you think you could make it work? i really appreciate you stepping forward 
and trying to update i unfortunaly didnt have much time lately..

**Comment by ThorstenBux** [comment]
I think I can. But I don't have much experience with creating an NPM component. I just wonder why I didn't pick up the latest master. At the moment it looks like a big mess. But I try to clean it up 👍

**Comment by nadavshemesh** [comment]
awesome! i think it will be much more useful to people if its compatible with angular 4
and to be honest i don't have much experience either :)

**Pull request merged**
